### ISSUE TITLE
Unable to schedule transaction without callData

### ISSUE THREAD

**Issue by kosecki123** [ethereum-alarm-clock/eac.js#10]
By default, the scheduling script is setting empty string which leads to an error during execution.

**Comment by pipermerriam** [comment]
What exactly is the error that occurs?

**Comment by kosecki123** [comment]
```

    toAddress   - 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
    callData    - 
    callGas     - 3000000
    callValue   - 100
    windowSize  - 100
    windowStart - 100
    gasPrice    - 100
    donation    - 100
    payment     - 100

    Sending from 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
    
Are all of these variables correct? [Y/n]



✖ Something went wrong! See the error message below.

Error: Given parameter is not bytes: ""
    at SolidityTypeDynamicBytes.formatInputDynamicBytes [as _inputFormatter] (/Users/piotrkosinski/Projects/ethereum-alarm-clock-js/node_modules/web3-eth-abi/src/formatters.js:83:15)
    at SolidityTypeDynamicBytes.SolidityType.encode (/Users/piotrkosinski/Projects/ethereum-alarm-clock-js/node_modules/web3-eth-abi/src/type.js:188:17)
    at /Users/piotrkosinski/Projects/ethereum-alarm-clock-js/node_modules/web3-eth-abi/src/index.js:255:29
    at Array.map (<anonymous>)
    at ABICoder.encodeParameters (/Users/piotrkosinski/Projects/ethereum-alarm-clock-js/node_modules/web3-eth-abi/src/index.js:254:34)
    at /Users/piotrkosinski/Projects/ethereum-alarm-clock-js/node_modules/web3-eth-contract/src/index.js:420:24
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/Users/piotrkosinski/Projects/ethereum-alarm-clock-js/node_modules/web3-eth-contract/src/index.js:419:12)
    at Object._processExecuteArguments (/Users/piotrkosinski/Projects/ethereum-alarm-clock-js/node_modules/web3-eth-contract/src/index.js:735:39)
    at Object._executeMethod (/Users/piotrkosinski/Projects/ethereum-alarm-clock-js/node_modules/web3-eth-contract/src/index.js:760:54)
    at schedule (/Users/piotrkosinski/Projects/ethereum-alarm-clock-js/src/scheduler.js:44:7)
    at <anonymous>
```

**Comment by pipermerriam** [comment]
Ah, I was interpreting your statement to mean it was a contract bug instead of a JS bug.
